name: 20200816-basic-docker-build

on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          registry: docker.pkg.github.com
          username: 74th
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: 20200816-basic/Dockerfile
          repository: 74th/try-github-container-registry/nginx
          tags: latest
